version: '3'
services:
  web:
    container_name: backend
    build: .
    command: python manage.py runserver 0.0.0.0:9000
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    depends_on:
      - db
    restart: always
    
  db:
    container_name: mysql_db
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306  # cannot change this port to other number
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=lms
      - MYSQL_USER=mindfire
      - MYSQL_PASSWORD=mindfire
      - MYSQL_ROOT_PASSWORD=better_2024
    
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
    driver: local
